### ISSUE TITLE
 Built fonts aren't showing up on notofonts.github.io

### ISSUE THREAD

**Issue by iwsfutcmd** [notofonts/duployan#4]
"Latest fonts" section [here](https://notofonts.github.io/#duployan) is blank. Nothing in the notofonts.github.io repository either.

Noto Sans Duployan is being distributed by Google Fonts, so I assume this is an oversight rather than not yet having a released version.

**Comment by simoncozens** [comment]
I've just cut a release, so things should show up tomorrow.
