### ISSUE TITLE
Too small dots

### ISSUE THREAD

**Issue by Mercury13** [notofonts/duployan#5]
### Title 
Dots are too small

### Font 
NotoSansDuployan-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2013-01-10

### Font Version
3.001

### OS name and version
W10 22H2

### Application name and version
Qt 6.1.3, probably all apps

### Issue
  1. Write anything containing dots
  2. Dots are barely seen
  3. Dots should be larger

### Character data
All characters with dots, e.g. U+1BC26 Duployan letter S with dot below

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/211663244-89c1f3d9-cecb-4dd4-ad15-10fca1e8e27f.png)

**Comment by dscorbett** [comment]
How prominent should dots be? Do you have any examples from primary sources?

**Comment by Mercury13** [comment]
> How prominent should dots be? Do you have any examples from primary sources?

No, you should do that depending on readability.

**Comment by Mercury13** [comment]
Well, I’ve found.
![image](https://user-images.githubusercontent.com/10164882/212487065-295b7047-52ef-4758-b834-e0e5f82f7dbc.png)
Here dots are thicker than lines, and also for readability.
[Perrault 1918]

**Comment by Mercury13** [comment]
IDK which shorthand English uses now, but those times people used nibs, and dot made with nib pen is thicker than line. Dots made with ballpoint are almost invisible. Some other manual (Sloan?) suggested pencil. So just use simple readability: you don’t simulate anyone’s writing, you make “spherical cow” shorthand on computer screen.

**Comment by Mercury13** [comment]
About spherical cow: I tried to draw two joined arcs, and it made me stop for a moment. Experienced stenographer should not do this, so he’ll surely draw some easing curve. That’s really hard for OpenType, and our font already has 10k glyphs and 500 rules…

**Comment by dscorbett** [comment]
Here is ⟨𛰀𛱌𛰦𛱓;𛰘𛱚𛰒⟩ <U+1BC00, U+1BC4C, U+1BC26, U+1BC53, U+003B, U+1BC18, U+1BC5A, U+1BC12> in the current font:
![𛰀𛱌𛰦𛱓;𛰘𛱚𛰒](https://user-images.githubusercontent.com/1124347/212574107-9dd8ec25-c8bb-4f42-becf-cc17ec729cf3.png)
Here it is with larger dots:
![𛰀𛱌𛰦𛱓;𛰘𛱚𛰒](https://user-images.githubusercontent.com/1124347/212574123-b5c7f7f6-0a74-4f78-9e7b-8e54d91ca1a1.png)
What do you think?

**Comment by Mercury13** [comment]
Think by legibility, but I like.

**Comment by Mercury13** [comment]
The only thing: maybe make dots inside tight circles just a bit smaller because of pixel-hinting — for them even 1 pixel is not zero, but errors of pixel-hinting become less prominent.

**Comment by Mercury13** [comment]
![image](https://user-images.githubusercontent.com/10164882/212751344-db4ac0b9-dd58-423a-93ed-10e95fc699d6.png)
Here’s a screenshot of CURRENT font: dots in tight circles work OK, but other dots are barely seen and merge with rendering glitches and even with dirt on screen.

**Comment by Mercury13** [comment]
Make upper dot of semicolon as big as semicolon’s comma, not as shorthand dots.

**Comment by Mercury13** [comment]
>Here’s a screenshot of CURRENT font: dots in tight circles work OK, but other dots are barely seen and merge with rendering glitches and even with dirt on screen.

Of course, semicolon is GitHub’s here, not yours.

**Comment by Mercury13** [comment]
> ![image](https://user-images.githubusercontent.com/10164882/212751344-db4ac0b9-dd58-423a-93ed-10e95fc699d6.png) Here’s a screenshot of CURRENT font: dots in tight circles work OK, but other dots are barely seen and merge with rendering glitches and even with dirt on screen.

Of course, semicolon is GitHub’s here, not yours.

**Comment by dscorbett** [comment]
I have reverted the enclosed dots of U+1BC56, U+1BC58, U+1BC5A, and U+1BC60. The pixel rounding is not consistently better one way or the other (larger vs. smaller enclosed dots), but smaller dots do generally seem less susceptible to problems caused by slight glyph misplacement. Also, there was barely enough space in U+1BC60 DUPLOYAN LETTER WOW for a large dot.

The upper dot of a semicolon is a shorthand dot: it is a dot in a character used in a shorthand. There is no reason punctuation dots need to look different from letter dots. Lots of fonts don’t make the top and bottom parts of semicolon the same size. So that glyph does not need changing.
